image: archlinux
packages:
sources:
    - https://git.sr.ht/~lucaz/charwild
triggers:
    - action: email
      condition: failure
      to: "<vollowx@outlook.com>"
tasks:
    - build: |
             cd charwild
             make -k
submitter:
    git.sr.ht:
        enabled: true
        allow-refs:
            - refs/heads/main
            - "refs/tags/*"
